services:
  dns1-bind9:
    image: ghcr.io/dagorret/dns1.com.ar:v1.1.0
    container_name: dns1-bind9
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "853:853/tcp"
      - "8080:8080/tcp"
    volumes:
      - ./bind-config:/etc/bind
      - dns-cache:/var/cache/bind
      - dns-run:/var/run/named
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: 512M

volumes:
  dns-cache:
  dns-run:
