// BIND 9.20.21 - DNS1 Argentina
options {
    directory "/var/cache/bind";
    listen-on { any; };
    listen-on-v6 { none; };
    recursion yes;
    allow-recursion { any; };
    max-cache-size 256M;
    query-source port * address *;
    dnssec-validation auto;
    rate-limit {
        responses-per-second 20;
        nxdomains-per-second 10;
        errors-per-second 5;
        all-per-second 80;
        window 15;
        slip 2;
        qps-scale 250;
        ipv4-prefix-length 32;
        ipv6-prefix-length 56;
    };
    prefetch 3600;
    querylog no;
};
zone "." IN {
    type hint;
    file "/etc/bind/db.root";
};
logging {
    channel default_syslog {
        syslog local2;
        severity notice;
    };
    category default {
        default_syslog;
    };
};
